version: '3.8'
services:
  backend:
    container_name: go-gin
    build:
      context: .
      target: prod
    tty: true
    platform: linux/x86_64
    volumes:
      - .:/go/src
    ports:
      - "3000:80"
    environment:
            TZ: Asia/Tokyo
    depends_on:
      - db

  db:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      # - type: volume
      #   source: mysql_test_volume
      #   target: /var/lib/mysql
    # networks:
    #   - golang_test_network
